#in built functions of list
l=[5,3,4,8,1,7]
l.append(6)
print("list after apeend",l)
l.extend([1,2,3])
print("list after extend",l)
l.insert(2,10)
print("list after insert",l)
l.remove(4)
print("list after remove",l)
ele=l.pop()
print("list after pop",l)
print("popped element",ele)
index=l.index(8)
print("index of 8 is ",index)
count=l.count(1)
print("count of 1",count)
l.sort()
print("list after sort",l)
l.reverse()
print("list after reverse",l)
l.clear()
print("list after clear",l)
